version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dvla
      POSTGRES_PASSWORD: dvla@gov.uk
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: dvla
      SPRING_DATASOURCE_PASSWORD: dvla@gov.uk
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    ports:
      - '8080:8080'

  node-proxy:
    build:
      context: ./node-proxy/
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - app

  react-client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - node-proxy

volumes:
  postgres-data:
